const services = [
  { id: "mini", name: "微光肖像", en: "WARM PORTRAIT", price: "NT$1,800 起", time: "7–10 個工作天", detail: "10 × 15 cm 精緻肖像畫；含一次草稿確認與一次細節調整。", tone: "peach", image: "/works/mini-portrait.png" },
  { id: "classic", name: "經典人像", en: "CLASSIC PORTRAIT", price: "NT$4,200 起", time: "14–21 個工作天", detail: "20 × 25 cm 客製肖像；含構圖討論、一次草稿確認與一次細節調整。", tone: "sage", image: "/works/classic-portrait.png" },
  { id: "memory", name: "記憶修復", en: "MEMORY RESTORATION", price: "NT$3,200 起", time: "7–14 個工作天", detail: "老照片數位修復與重製；依原始照片破損程度與輸出尺寸報價。", tone: "ink", image: "/works/memory-restoration.png" },
];

const deliveredWorks = [
  { id: "warm", name: "微光肖像", en: "WARM PORTRAIT", detail: "小幅原作 · 已完成交付", tone: "peach", image: "/works/mini-portrait.png" },
  { id: "classic", name: "經典人像", en: "CLASSIC PORTRAIT", detail: "客製肖像委託 · 已完成交付", tone: "sage", image: "/works/classic-portrait.png" },
  { id: "memory", name: "記憶修復", en: "MEMORY RESTORATION", detail: "老照片修復委託 · 已完成交付", tone: "ink", image: "/works/memory-restoration.png" },
];

export default function Home() {
  return <main>
    <div className="announcement">客製委託開放中 · 報價確認後才進入製作</div>
    <nav className="nav" aria-label="主選單"><a className="brand" href="#top"><span>繪畫人像與</span>照片技術工紡</a><div className="nav-links"><a href="#shop">商店</a><a href="#how">委託方式</a><a href="#archive">成果牆</a><a href="#contact">客服</a></div></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">PORTRAIT PAINTING &amp; PHOTOGRAPHIC TECHNOLOGY</p><h1>把時間，<br /><i>畫成肖像。</i></h1><p className="intro">客製人像繪畫與老照片修復服務。從照片、構圖到交付，每件作品皆由工作室一對一確認。</p><div className="hero-actions"><a className="button" href="#shop">查看委託服務 <span>↓</span></a><a className="text-link" href="#contact">立即詢價 ↗</a></div></div><div className="portrait-frame" aria-label="抽象人像展示圖"><div className="sun" /><div className="face"><span className="eye left" /><span className="eye right" /><span className="nose" /><span className="mouth" /></div><p>STUDIO / 2026</p></div></section>
    <section className="trust"><div><b>客製報價</b><span>依尺寸、照片與需求確認</span></div><div><b>草稿確認</b><span>製作前先確認人物與構圖</span></div><div><b>安全交付</b><span>台灣本島宅配，運費於報價單列示</span></div></section>
    <section className="shop" id="shop"><div className="section-head"><p className="eyebrow">COMMISSION SHOP</p><h2>選擇一種方式，<br />把記憶留下來。</h2><p className="section-intro">以下為服務起價；最終報價將依照片狀況、人物數量、尺寸與交付形式確認。</p></div><div className="product-grid">{services.map((service) => <article className={`product ${service.tone}`} key={service.id}><div className="product-art"><img src={service.image} alt={`${service.name} 成品示意`} /></div><p className="eyebrow">{service.en}</p><h3>{service.name}</h3><p className="service-price">{service.price}</p><p className="product-detail">{service.detail}</p><dl className="service-meta"><div><dt>製作工期</dt><dd>{service.time}</dd></div><div><dt>付款方式</dt><dd>報價確認後提供 EzPay 付款連結</dd></div></dl><div className="product-bottom"><span>OPEN FOR COMMISSIONS</span><a href="#contact">開始委託 <span>↗</span></a></div></article>)}</div></section>
    <section className="how" id="how"><p className="eyebrow">HOW TO COMMISSION</p><h2>清楚確認，<i>再開始創作。</i></h2><div className="steps"><div><b>01</b><h3>送出委託需求</h3><p>填寫想製作的服務、照片狀況與希望交付時間。</p></div><div><b>02</b><h3>收到客製報價</h3><p>工作室在 2 個工作天內回覆可行性、報價、工期與付款連結。</p></div><div><b>03</b><h3>照片與草稿確認</h3><p>付款後提供照片；草稿確認完成才進入正式製作。</p></div><div><b>04</b><h3>製作與寄送</h3><p>完成後通知並以宅配寄送；數位檔案以下載連結交付。</p></div></div></section>
    <section className="policy" id="policy"><div className="section-head"><p className="eyebrow">SHOP POLICY</p><h2>購買與交付<br />說明。</h2></div><div className="policy-grid"><article><h3>付款與工期</h3><p>報價單確認後以 EzPay 線上付款完成訂金或全額款項。工期自照片與草稿確認翌日起計算；遇國定假日或照片需額外修復時，將另行通知。</p></article><article><h3>寄送方式</h3><p>實體作品採台灣本島宅配寄送，運費於報價單列示；離島與海外訂單需另行報價。數位修復檔以下載連結交付，不寄送實體物。</p></article><article><h3>修改、取消與退換貨</h3><p>每件委託含一次草稿確認與一次細節調整。草稿確認前可申請取消；客製作品進入正式製作後，不接受因個人喜好退換貨。若運送造成明顯損壞，請於收件 48 小時內附照片聯絡客服。</p></article><article><h3>客服與回覆時間</h3><p>客服於週一至週五 10:00–18:00 回覆，國定假日順延。一般委託與售後問題將於 2 個工作天內回覆。</p></article></div></section>
    <section className="shop" id="archive"><div className="section-head"><p className="eyebrow">COMPLETED COMMISSIONS</p><h2>已交付的作品，<br />成為某個人的珍藏。</h2><p className="section-intro">為保護委託人隱私，成果牆不公開成交金額與個人資料。</p></div><div className="product-grid">{deliveredWorks.map((product) => <article className={`product ${product.tone}`} key={product.id}><div className="product-art"><img src={product.image} alt={`${product.name} 成品紀錄`} /></div><p className="eyebrow">{product.en}</p><h3>{product.name}</h3><p className="product-detail">{product.detail}</p><div className="product-bottom"><span>COMMISSION ARCHIVE</span><span className="delivered">已交付</span></div></article>)}</div></section>
    <section className="contact" id="contact"><div><p className="eyebrow">CUSTOMER SERVICE</p><h2>準備好照片後，<br /><i>就可以開始。</i></h2><p>填寫委託需求後，工作室會在 2 個工作天內回覆報價與製作安排。</p><p className="contact-email">客服信箱：<a href="mailto:charlesree826@gmail.com">charlesree826@gmail.com</a></p></div><form className="contact-form" action="mailto:charlesree826@gmail.com" method="post" encType="text/plain"><label>姓名<input name="姓名" required /></label><label>電子信箱或電話<input name="聯絡方式" required /></label><label>想委託的服務<select name="委託服務" defaultValue="微光肖像"><option>微光肖像</option><option>經典人像</option><option>記憶修復</option><option>其他客製委託</option></select></label><label>照片與需求說明<textarea name="需求說明" rows={4} required placeholder="例如：人物數量、希望尺寸、照片狀況與交付時間"></textarea></label><button className="button light" type="submit">送出委託需求 <span>↗</span></button><p className="form-note">送出後會開啟你的電子郵件程式；請確認收件資訊後再寄出。</p></form></section>
    <footer><span>© 2026 繪畫人像與照片技術工紡</span><span>Portrait Painting and Photographic Technology</span></footer>
  </main>;
}
